import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });

const ClientProviders = dynamic(() => import("@/components/ClientProviders"), {
  ssr: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
